services:
  db:
    image: mysql:9.2
    container_name: mysql_db
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: django_app
    restart: always
    depends_on:
      - db
    env_file: .env
    environment:
      DB_HOST: db
      DB_PORT: 3306
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles  
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "my_site.wsgi:application"]

volumes:
  mysql_data:
  static_volume: 

