# Generated by Django 5.1.5 on 2025-01-26 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Paste a link to a YouTube video for this recipe.",
                max_length=255,
                null=True,
                validators=[django.core.validators.URLValidator()],
                verbose_name="YouTube Video",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image for this recipe.",
                null=True,
                upload_to="recipe_images/",
                verbose_name="Recipe Image",
            ),
        ),
    ]
