# Generated by Django 5.1.5 on 2025-01-26 13:43

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_recipeimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeimage",
            name="alt",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text="Provide step-by-step instructions for the recipe.",
                null=True,
                verbose_name="Recipe Instructions",
            ),
        ),
    ]
