# Generated by Django 5.1.5 on 2025-01-26 17:29

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_recipeimage_alt_alter_recipe_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image for this recipe.",
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="",
                verbose_name="Recipe Image",
            ),
        ),
    ]
