# Generated by Django 5.1.5 on 2025-01-28 16:40

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_alter_recipe_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="cuisine_type",
            new_name="cuisine_type_id",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="difficulty_level",
            new_name="difficulty_level_id",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="dish_type",
            new_name="dish_type_id",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="event_type",
            new_name="event_type_id",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="main_ingredient",
            new_name="main_ingredient_id",
        ),
        migrations.AlterField(
            model_name="recipeimage",
            name="image",
            field=models.ImageField(
                help_text="Upload additional images for this recipe.",
                storage=storages.backends.s3.S3Storage(),
                upload_to="",
                verbose_name="Recipe Gallery Image",
            ),
        ),
    ]
