# Generated by Django 5.1.5 on 2025-01-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_rename_cuisine_type_recipe_cuisine_type_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dishtype",
            name="slug",
            field=models.SlugField(
                help_text="A unique slug for the dish type.",
                null=True,
                unique=True,
                verbose_name="URL Slug",
            ),
        ),
    ]
