# Generated by Django 5.1.5 on 2025-01-29 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_dishtype_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="cuisine_type_id",
            new_name="cuisine_type",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="difficulty_level_id",
            new_name="difficulty_level",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="dish_type_id",
            new_name="dish_type",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="event_type_id",
            new_name="event_type",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="main_ingredient_id",
            new_name="main_ingredient",
        ),
    ]
