# Generated by Django 5.1.5 on 2025-01-30 17:24

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_rename_cuisine_type_id_recipe_cuisine_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alt", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload additional images for the gallery.",
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="",
                        verbose_name="Gallery Image",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
