# Generated by Django 5.1.5 on 2025-01-31 16:00

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_galleryimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("paragraph", models.CharField(max_length=150)),
                ("cta_1_text", models.CharField(max_length=50)),
                ("cta_1_link", models.CharField(max_length=255)),
                ("cta_2_text", models.CharField(max_length=50)),
                ("cta_2_link", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload Image to the slider.",
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="",
                        verbose_name="Slide Image",
                    ),
                ),
                ("alt", models.CharField(blank=True, max_length=150, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="dishtype",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A brief description of the dish type.",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="dishtype",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image for the dish type.",
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="dish_types",
                verbose_name="Dish Type Image",
            ),
        ),
    ]
