# Generated by Django 5.1.5 on 2025-01-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_slide_dishtype_description_dishtype_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="slide",
            name="subtitle",
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
