# Generated by Django 5.1.5 on 2025-01-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_slide_subtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slide",
            name="cta_1_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="slide",
            name="cta_1_text",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="slide",
            name="cta_2_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="slide",
            name="cta_2_text",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
