# Generated by Django 5.1.5 on 2025-01-31 16:29

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0012_alter_slide_cta_1_link_alter_slide_cta_1_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryimage",
            name="image",
            field=models.ImageField(
                help_text="Upload additional images for the gallery.",
                storage=storages.backends.s3.S3Storage(),
                upload_to="gallery",
                verbose_name="Gallery Image",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image for this recipe.",
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="recipe",
                verbose_name="Recipe Image",
            ),
        ),
        migrations.AlterField(
            model_name="recipeimage",
            name="image",
            field=models.ImageField(
                help_text="Upload additional images for this recipe.",
                storage=storages.backends.s3.S3Storage(),
                upload_to="recipe_images",
                verbose_name="Recipe Gallery Image",
            ),
        ),
        migrations.AlterField(
            model_name="slide",
            name="image",
            field=models.ImageField(
                help_text="Upload Image to the slider.",
                storage=storages.backends.s3.S3Storage(),
                upload_to="slider",
                verbose_name="Slide Image",
            ),
        ),
    ]
