# Generated by Django 5.1.5 on 2025-02-01 07:44

import django.db.models.deletion
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0013_alter_galleryimage_image_alter_recipe_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="cover_picture",
            field=models.ImageField(
                blank=True,
                help_text="Upload a cover picture for this recipe.",
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="recipe",
                verbose_name="Recipe Cover Picture",
            ),
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "recipe",
                    models.ForeignKey(
                        help_text="Select the recipe associated to this ingredient.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingredients",
                        to="portfolio.recipe",
                        verbose_name="Recipe",
                    ),
                ),
            ],
        ),
    ]
