name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: cooking_blog_database
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=localhost --silent"
          --health-timeout=30s
          --health-retries=3
          --health-start-period=10s
          --health-interval=10s


    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Run Migrations
        run: python manage.py migrate

      - name: Run Tests
        env:
            DB_ENGINE: django.db.backends.mysql
            DB_NAME: cooking_blog_database
            DB_USER: root
            DB_PASSWORD: ''
            DB_HOST: mysql
            DB_PORT: 3306
        run: |
          python manage.py test