name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: 3.8

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./web/requirements.txt

      - name: Run Tests'
        env:
          SECRET_KEY: django-insecure-8elby-6f67+t@y-9oy-zwod668xu=l$bd@r4z6xxlip$a08ark
          DB_NAME: cooking_blog_database
          DB_USER: root
          DB_PASSWORD: ''
          DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
        run: |
          python ./web/manage.py test
