name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Run Tests
        env:
          DB_NAME: cooking_blog_database
          DB_USER: root
          DB_PASSWORD: ''
          DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
          DJANGO_SECRET_KEY: django-insecure-8elby-6f67+t@y-9oy-zwod668xu=l$bd@r4z6xxlip$a08ark
          ENGINE: django.db.backends.mysql
        run: |
          python manage.py test