name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:9.2
        env:
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: cooking_blog_database
        ports: ['3306:3306']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Run Migrations
        run: python manage.py migrate
        env: 
          DB_ENGINE: django.db.backends.mysql
          DB_NAME: cooking_blog_database
          DB_USER: root
          DB_PASSWORD: ''
          DB_HOST: 127.0.0.1
          DB_PORT: 3306

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h "127.0.0.1" --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 2
          done

      - name: Run Tests
        env:
          DB_ENGINE: django.db.backends.mysql
          DB_NAME: cooking_blog_database
          DB_USER: root
          DB_PASSWORD: ''
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
        run: |
          python manage.py test